# Add application configuration variables here, as shown below.
#
# GOOGLE_BROWSER_KEY: yourgooglebrowserkey
# GOOGLE_CLIENT_ID: yourgoogleclientid
# GOOGLE_CLIENT_SECRET: yourgooglesecret

# Generate a new secret token using rake secret
# SECRET_TOKEN: c84bd592aa38b350baea393fe63bf7bf462d4016884fbeaa405bb88783209e0576063fb8c77dfe3d65ec862450cb4aa91bf73867b7632d64eea58b09ffb65943
# SECRET_KEY_BASE: 0a08ea7ba310aff66fe967a6a60cf8f87e4f4b721166f94a94361563ffb2f5266e027878e16efe7b66049b057717238615f628d84db8c0af356293d184fc49a5

# NewRelic
# NEWRELIC_LICENSE_KEY:

#development:
#  MAILER_INTERCEPTOR: user@virginiafirst.org
#  MAILER_DELIVERY_METOHD: smtp
#  MAILER_SMTP_SERVER: smtp.gmail.com
#  MAILER_SMTP_PORT: 587
#  MAILER_SMTP_DOMAIN: virginiafirst.org
#  MAILER_SMTP_USERNAME: user@virginiafirst.org
#  MAILER_SMTP_PASSWORD: y0urP@ssw0rd

#production:
#  MAILER_DELIVERY_METHOD: sendmail
